### ISSUE TITLE
Errors when upgarding to Flutter 3.27

### ISSUE THREAD

**Issue by JeffOlajos** [ethanblake4/flutter_eval#95]
I get several flutter_eval errors when upgrading to the latest flutter realese in the stable channel. Color methods not defined and open_fileX.

**Comment by Praveen-Pandiyan** [comment]
+1

**Comment by tusharsainx** [comment]
yes, similar happening to dart_eval. Unable to compile the hot update patch
Here is the link to an opened issue. https://github.com/ethanblake4/dart_eval/issues/226

**Comment by Zverik** [comment]
See #96.

**Comment by Zverik** [comment]
For a quick solution, you can add an override to pubspec.yaml:

```yaml
dependency_overrides:
  flutter_eval:
    git:
      url: https://github.com/Zverik/flutter_eval.git
      ref: flutter_3_27
```
